### PR TITLE
Create oep-0010-proc-openedx-releases.rst

### PR DESCRIPTION
**Pull request by michellephilbrick**
Added TL;DR and visual. 

Possibly remove text Component & Support sections if they are covered in the visual?

### CODE REVIEW

**Comment by nedbat** [comment]
@michellephilbrick Thanks for doing this!
I'm concerned the visual will reduce the accessibility of the text.  Words in images can't be  indexed by search engines, for example, or translated by Google Translate.  In this case, I think I would skip the visual.  It doesn't provide much semantic enhancement.  What do you think?

**Comment by sarina** [comment]
@michellephilbrick I'm happy to get this finished up for you. I would need the visual.

@nedbat We can put alt text for visuals. Other OEPs also contain visuals.

**Comment by mphilbrick211** [comment]
Hi @sarina - we can close for now. Once the conference stuff is a bit quieter I'll take a closer look at the tl;drs - they're on my list, just have to get through some urgent things beforehand!

**Comment by sarina** [comment]
Totally understand @mphilbrick211 - let me know how I can help out post-conference 😄

**Pull request closed without merging**
