### PR TITLE
A draft of Change Transparency

### PR DESCRIPTION
**Pull request by nedbat**
It's not clear this will become an OEP, but I needed someplace to write
this all down.

### CODE REVIEW

**Comment by antoviaque** [comment]
@nedbat Great to see this! :D Definitely +1 :+1: 

Is it related to https://github.com/edx/open-edx-proposals/issues/171 ?

**Comment by nedbat** [comment]
@antoviaque yes, in the discussion on the PR itself (https://github.com/edx/edx-platform/pull/25949) we were talking about wanting to record the motivations for the information collected in the PR template.

**Comment by feanil** [comment]
@nedbat do you think we still need this high-level OEP around change transparency?

**Comment by sarina** [comment]
@nedbat the PR template, https://raw.githubusercontent.com/openedx/edx-platform/master/.github/pull_request_template.md, references this PR. Is that still the right thing to do?

**Comment by nedbat** [comment]
@sarina You are right that we were too optimistic.... I'll update the template.

**Pull request closed without merging**
