### PR TITLE
OEP-0020: Blockstore

### PR DESCRIPTION
**Pull request by bradenmacdonald**
This is a placeholder OEP for the Harvard LabXchange Blockstore proposal, which is in the early draft stages:
https://openedx.atlassian.net/wiki/spaces/AC/pages/681673391/Harvard+LabXchange+Blockstore+Proposal

Development of this proposal is being funded by Harvard LabXchange and the Amgen Foundation, with significant in-kind contributions from edX.

FYI @ormsbee @nasthagiri @nedbat

### CODE REVIEW

**Comment by albemarle** [comment]
@bradenmacdonald Do we still need this PR?

**Comment by pdpinch** [comment]
I'm still game to be arbiter if need be.

**Comment by edx-webhook** [comment]
Thanks for the pull request, @bradenmacdonald! I've created [OSPR-5503](https://openedx.atlassian.net/browse/OSPR-5503) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by natabene** [comment]
@bradenmacdonald Thank you for the contribution, sorry it has been a while.

**Comment by sarina** [comment]
@bradenmacdonald At this point the original commit is nearly 4 years old, could we close this PR until it is ready for review?

**Comment by feanil** [comment]
Given that this is empty and that the blockstore repo has a bunch of good links and info in it, I'm gonna close this for now and we can always re-open it if we think there needs to be an OEP entry for this.

**Comment by edx-webhook** [comment]
Although this pull request is already closed, I've created [OSPR-6452](https://openedx.atlassian.net/browse/OSPR-6452) so that we can track it in Jira.

There is nothing you have to do. No action is needed from your side.  Thanks.

**Comment by bradenmacdonald** [comment]
@feanil Sounds good.

**Pull request closed without merging**
