### PR TITLE
docs: recommend Renovate instead of Greenkeeper

### PR DESCRIPTION
**Pull request by brian-smith-tcril**
Most of this ADR is just copied from https://openedx.atlassian.net/wiki/spaces/AC/pages/1841791377/Set+up+Renovate+to+Automate+JavaScript+Dependency+Updates

I also noticed we had both `0007-bundle-size.rst` and  `0007-typescript.rst`. The typescript ADR was showing up as number 8 on the list so I updated the filename to reflect that.

### CODE REVIEW

**Review by feanil — APPROVED** [review]

**Review by sarina — COMMENTED** [review]
@brian-smith-tcril could you please add a Changelog entry to the OEP?

**Comment by sarina** [comment]
You also need to update the redirects, see https://github.com/openedx/open-edx-proposals/pull/585/files for an example

**Comment by brian-smith-tcril** [comment]
@sarina I added a changelog entry and a redirect https://github.com/openedx/open-edx-proposals/compare/b51a7a49a4787df4436c956ccf9d44f0dd4676a3..b989856ddd101feb3917d8791ab1d045d7acbc68 and then fixed a mistake in my redirect https://github.com/openedx/open-edx-proposals/compare/b989856ddd101feb3917d8791ab1d045d7acbc68..506478e9da91dac84817830fe04910572a4ab332

**Review by sarina — APPROVED** [review]

**Comment by sarina** [comment]
Thanks!!!

**Pull request merged**
