### PR TITLE
OEP-XXXX: Micro-frontend plugins

### PR DESCRIPTION
**Pull request by davidjoy**
This is a work in progress - it needs its guts fleshed out significantly, but contains a rough structure and an abstract, motivation, and specification.

Parent epic: https://github.com/openedx/platform-roadmap/issues/27

### CODE REVIEW

**Comment by feanil** [comment]
@davidjoy same question here, what's the status of this OEP, should it be closed for now or is it gonna come out of draft some time soon?

**Comment by davidjoy** [comment]
Same sad response - I still think this is the right proposal but it's off my radar at the moment.  This one is significantly further away from completion than the other.

**Comment by arbrandes** [comment]
Same deal as on #259: this is being considered as part of our MFE roadmap priorization work: see [this cell](https://docs.google.com/spreadsheets/d/1zXBzPMrvRfz0VmygndqzN1qHSe95m6U0E-aNVwx00DA/edit#gid=0&range=I3) on the priorities document. This document will be ported over to issues on [the Roadmap](https://github.com/orgs/openedx/projects/4/views/1) shortly.

I'm assigning myself here as well.

**Comment by davidjoy** [comment]
I'm going to close this out for now; I don't think anyone is planning on finishing this OEP, and I don't have the capacity to get back to it, sadly.  If someone wants to revive it, feel free to reopen.

**Pull request closed without merging**
